#!/usr/bin/env python3
"""reports/ability-placement-probe.md from the probe's JSON outputs (investigation only)."""
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD = os.path.join(HERE, "build")


def jl(n):
    return json.load(io.open(os.path.join(BUILD, n), encoding="utf-8"))


# Hand judgments of the seeded 30-ability sample (read against the leaf's members). The sample
# itself and every number beside it are computed; only the verdict column is human.
VERDICT = {
    "Charforger": ("wrong detail", "oil counter matched to the +1/+1-counter leaf: counter type is not a token"),
    "Three Steps Ahead": ("generic", "a bare eff:Draw leaf of 971 cards; the mode's text is blank"),
    "Candy Trail": ("real", "scry leaf, all members scry"),
    "Truck Toss": ("real", "cost-reduction leaf"),
    "Aerith Gainsborough": ("real", "+1/+1 counter on itself"),
    "Sethron, Hurloon General": ("generic", "bare eff:Token leaf of 992 cards: says only 'makes a token'"),
    "Flameskull": ("real", "can't-block leaf"),
    "Soaring Lightbringer": ("generic", "bare eff:Token leaf"),
    "War of the Last Alliance": ("wrong", "Saga lore-counter replacement matched to the +1/+1-counter leaf"),
    "Grunn, the Lonely King": ("real", "enters with +1/+1 counters"),
    "Satoru Umezawa": ("real", "look-at-the-top leaf"),
    "Sazh Katzroy": ("real", "counter on target creature (the 'then double' half is not a token)"),
    "Gnawing Vermin": ("real", "-1/-1 on an opponent's creature"),
    "Angelic Shield": ("real", "static buff for creatures you control"),
    "Sanctuary Lockdown": ("real", "tap target opposing creature"),
    "Prophet of Kruphix": ("real", "cast-with-flash leaf (its derived phrase label is odd; the members are right)"),
    "Azorius Cluestone": ("generic", "bare eff:Draw leaf"),
    "Diregraf Captain": ("real", "target opponent loses life"),
    "The Thing": ("wrong", "only the first step of a reflexive chain is tokenised: matched on 'may pay', not on doubling counters"),
    "Sisay, Weatherlight Captain": ("generic", "the 440-card 'static Continuous on itself' catch-all"),
    "Myr Turbine": ("generic", "bare eff:Token leaf"),
    "Rydia, Summoner of Mist": ("real", "may discard"),
    "Force of Vigor": ("real", "destroy artifact or enchantment"),
    "Sanguine Spy": ("wrong", "same first-step-only artifact: matched on 'may pay 2 life', not on drawing"),
    "Ajani's Influence": ("real", "counters on target creature"),
    "Very Cryptic Command": ("real", "bounce mode (text blank in the data)"),
    "Deep-Slumber Titan": ("real", "'enters tapped' is the leaf's own phrase; its branch label 'Tapper' is misleading"),
    "Chrome Dome": ("real", "artifact-creature static"),
    "Nemata, Grove Guardian": ("generic", "bare eff:Token leaf"),
    "Resolute Rejection": ("generic", "bare eff:Draw leaf; mode text blank"),
}

NAMED_NOTES = {
    "Mulldrifter": "Fine. (Evoke is a keyword, outside the four buckets.)",
    "Spark Double": "FINDING: scores a perfect 1.000 on the +1/+1-counter leaf, but the parse lost the whole copy effect. A high score on a wrong parse.",
    "Sakura-Tribe Elder": "Fine: single ability, identical to its blended score.",
    "Hallowed Fountain": "FINDING: the pay-2-life replacement tokenises as a bare eff:LoseLife and scores 1.000 against 'each opponent loses', a wrong-looking leaf with no branch. The two mana abilities are bare eff:Mana (leaf 46, 526 cards).",
    "Psychosis Crawler": "Both abilities score 1.000, to different leaves: 'each opponent loses' (right) and the generic 440-card static catch-all 'as long as' (thin). Blended 0.778 sits just under the floor.",
    "Rhystic Study": "Fine, but the 'unless that player pays' is invisible to tokens.",
    "Wall of Omens": "Fine.",
    "Eternal Witness": "Matches its leaf, but that leaf's branches are 'Bounce removal / Spot removal'; returning a card from your graveyard is not removal. Branch label, not scorer, is wrong.",
    "Solemn Simulacrum": "Both abilities match different leaves (Tutor, Card draw); the card is already clustered in a combined leaf.",
    "Tireless Tracker": "Already clustered, yet its blended score against its own leaf is 0.779, below the 0.80 floor; per-ability scores are 0.997 and 1.000 to two different leaves.",
}


def pc(n, d):
    return "%s (%.1f%%)" % (format(n, ","), 100.0 * n / d) if d else str(n)


def main():
    o = jl("ability_probe.json")
    ex = jl("ability_probe_extra.json")
    named = jl("ability_probe_named.json")
    v = o["validation_clustered"]
    g2 = o["group2"]["all"]
    bands = o["group2_by_band"]
    L = []
    A = L.append

    A("# Per-ability scoring probe: would it rescue the unplaced cards?\n")
    A("Investigation only. Nothing is placed, nothing is re-clustered, no threshold or frozen file changed. "
      "Generated by `src/report_ability_probe.py` from `build/ability_probe.json`, "
      "`ability_probe_extra.json` and `ability_probe_named.json` (scorer: `src/ability_probe.py`, "
      "`run_ability_probe.py`, `probe_extra.py`, `probe_named_cards.py`).\n")

    A("## Bottom line\n")
    A("- **The diluted-blend mechanism is real and almost universal in the 0.70-0.80 band:** 951 of 953 cards "
      "have an ability scoring >= 0.90 against some leaf.")
    A("- **But the usual shape is not 'one perfect match + one stray'.** Of the 737 two-ability cards in that band, "
      "**718 have BOTH abilities >= 0.90, against two different leaves**, and only 19 fit the one-perfect-"
      "plus-one-unmatched story. These are genuine two-effect cards. Per-ability scoring does not find one "
      "better home for them; it finds two (or three). It is a multi-membership layer, not a re-placement.")
    A("- **Scores are bimodal** (almost everything is >= 0.99 or < 0.5), so the threshold barely matters: "
      "2,392 / 2,393 / 2,396 cards are rescued at 0.90 / 0.80 / 0.70.")
    A("- **A third of the rescues are low-information:** 712 of the 2,392 rescued cards match only generic leaves "
      "(a bare `eff:Draw`, `eff:Token` or `eff:Mana`, or a leaf of 500+ cards). Restricting to specific matches "
      "keeps 1,524.")
    A("- **Recommendation: build it, narrowly.** See the last section.\n")

    # ----------------------------------------------------------------- step 1 + 2
    A("## 1. The scorer\n")
    A("No feature space is invented. `src/ability_probe.py` rebuilds the clustering's own: the same vocabulary "
      "(insertion order over the 26,972 clustered + noise cards, 3,706 tokens), binary presence x IDF "
      "(`ln((1+n)/(1+df)) + 1`), L2 normalisation and leaf centroids (mean of clustered members' vectors, "
      "L2-normalised), exactly as `build_placements.py` does. One vector per ability item uses "
      "`card_features()`'s token rules restricted to that item (effect + target for abilities, triggers and "
      "replacements via `execute`; mode + `affected` for statics); each is scored by cosine against all 657 "
      "centroids.\n")
    A("Reproduction checks, all exact: the union of an item's tokens equals `card_features()` for all "
      f"{o['token_scheme_check']['clustered_faces']:,} clustered faces (0 mismatches); the blended score and best "
      f"leaf of all {o['group2_blend_reproduction']['cards']:,} cards in the unplaced group reproduce the "
      f"placement file's numbers ({o['group2_blend_reproduction']['blended_leaf_or_score_mismatch']} mismatches).\n")
    ic = o["items_clustered"]
    A(f"Ability items in clustered faces: **{ic['ability_items']:,}** (abilities {ic['by_bucket']['abilities']:,}, "
      f"triggers {ic['by_bucket']['triggers']:,}, statics {ic['by_bucket']['static_abilities']:,}, replacements "
      f"{ic['by_bucket']['replacements']:,}). **{ic['with_no_tokens']} produce no tokens** "
      f"({ic['with_no_tokens_by_bucket']}); none has tokens outside the vocabulary. In the unplaced group: "
      f"{o['items_group2']['ability_items']:,} items, {o['items_group2']['with_no_tokens']} with no tokens.\n")

    A("## 2. Validation on already-clustered cards (done before trusting anything else)\n")
    ex_ = v["single_ability_exactness"]
    A(f"**Single-ability exactness: passed.** {ex_['faces_with_exactly_one_token_bearing_item']:,} clustered faces "
      f"have exactly one token-bearing ability ({ex_['of_which_exactly_one_item_at_all']:,} have exactly one "
      f"ability item at all). In every one the ability vector and the card vector are bit-identical, and so are "
      f"all 657 scores: **{ex_['vector_or_score_not_bit_identical']} differences.**\n")
    b, bl = v["best_ability_vs_own_leaf"], v["blended_vs_own_leaf"]
    A("Against the card's **own** leaf:\n")
    A("| | faces | >= 0.90 | >= 0.80 | >= 0.70 | median | 5th pct |")
    A("|---|---:|---:|---:|---:|---:|---:|")
    A(f"| best single ability | {v['faces_scored']:,} | {pc(b['ge_0.90'], v['faces_scored'])} | {pc(b['ge_0.80'], v['faces_scored'])} | "
      f"{pc(b['ge_0.70'], v['faces_scored'])} | {b['percentiles']['50']} | {b['percentiles']['5']} |")
    A(f"| blended card vector | {v['faces_scored']:,} | {pc(bl['ge_0.90'], v['faces_scored'])} | {pc(bl['ge_0.80'], v['faces_scored'])} | "
      f"{pc(bl['ge_0.70'], v['faces_scored'])} | {bl['percentiles']['50']} | {bl['percentiles']['5']} |")
    mb, mbl = v["multi_best_ability_vs_own"], v["multi_blended_vs_own"]
    A(f"| ...multi-ability faces only ({v['multi_ability_faces']:,}): best ability | {v['multi_ability_faces']:,} | "
      f"{pc(mb['ge_0.90'], v['multi_ability_faces'])} | | | {mb['percentiles']['50']} | {mb['percentiles']['5']} |")
    A(f"| ...multi-ability faces only: blended | {v['multi_ability_faces']:,} | "
      f"{pc(mbl['ge_0.90'], v['multi_ability_faces'])} | | | {mbl['percentiles']['50']} | {mbl['percentiles']['5']} |\n")
    A(f"Best-ability score vs own leaf, decile histogram (0.0-0.1 ... 0.9-1.0): {b['hist10']}.\n")
    A("What this says. For a single-ability card the two scores are the same thing, as they must be. For a "
      "**multi-ability** card in its own leaf, the best single ability scores >= 0.90 in only 59% of faces "
      "against 72% for the blended vector, and in "
      f"{v['multi_ability_best_exceeds_blended']:,} multi-ability faces the best ability beats the blend. The "
      "existing leaves were built from blended vectors, so a card clustered into a combined leaf (Draw + "
      "Token, say) is a worse fit per ability than per card. **Per-ability scoring is a good detector of "
      "single-effect leaves and a poor fit for combined ones**, so it should not touch cards that already "
      "have a placement.\n")

    # ----------------------------------------------------------------- step 3
    A("## 3. The 0.70-0.80 band (953 cards)\n")
    bd = bands["0.70-0.80"]
    A("| measure | cards |")
    A("|---|---:|")
    A(f"| cards in the band | {bd['cards']} |")
    A(f"| one token-bearing ability (cannot be rescued: per-ability = blended) | {bd['one_bearing_ability']} |")
    A(f"| two or more token-bearing abilities | {bd['two_or_more_bearing']} (exactly two: 737, three: 167, four: 41, five: 6) |")
    A(f"| >= 1 ability scores >= 0.90 against some leaf | {pc(bd['rescued_any_ge_0.90'], bd['cards'])} |")
    A(f"| **every** ability scores >= 0.90 | {pc(bd['all_abilities_ge_0.90_multi'], bd['cards'])} |")
    A(f"| ...exactly two abilities, both >= 0.90, in the SAME leaf | 0 (by construction: then the blend would be high) |")
    A(f"| ...exactly two abilities, both >= 0.90, in DIFFERENT leaves | 718 |")
    A(f"| ...exactly two abilities, one >= 0.90 and one below | 19 |")
    A(f"| distinct leaves the card's >= 0.90 abilities land in | 1: 21 · 2: 752 · 3: 150 · 4: 27 · 5: 1 |")
    A(f"| best ability and best blended leaf are the **same** leaf | {bd['rescued_any_ge_0.90_same_leaf']} |")
    A(f"| best ability and best blended leaf **differ** | {bd['rescued_any_ge_0.90_different_leaf']} (in 516 of them the blended leaf is still some other ability's best leaf) |")
    A("")
    A(f"Best per-ability score, decile histogram (0.0 ... 1.0): {bd['best_ability_hist10']}; percentiles "
      f"{bd['best_ability_percentiles']}. Blended scores in the band: 115 sit at 0.700-0.715 (the 1/sqrt(2) "
      "signature); the rest spread to 0.80 because two abilities' tokens partly overlap. The current "
      "suggestion link is therefore not wrong so much as half the story: for 89% (850 of 953) it points at one "
      "of the card's abilities' best leaves.\n")

    # ----------------------------------------------------------------- step 4
    A("## 4. The whole unplaced group (4,175 cards)\n")
    A("Rescued = at least one ability scores >= the threshold against some leaf.\n")
    A("| blended band | cards | 1 ability only | 2+ abilities | rescued >= 0.90 | >= 0.80 | >= 0.70 | every ability >= 0.90 | rescued, >= 1 *specific* match | rescued only by *generic* matches |")
    A("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for name in ("0.70-0.80", "0.50-0.70", "<0.50"):
        d, e = bands[name], ex[name]
        A(f"| {name} | {d['cards']:,} | {d['one_bearing_ability']:,} | {d['two_or_more_bearing']:,} | "
          f"{pc(d['rescued_any_ge_0.90'], d['cards'])} | {d['rescued_any_ge_0.80']:,} | {d['rescued_any_ge_0.70']:,} | "
          f"{d['all_abilities_ge_0.90_multi']:,} | {e.get('rescued_with_>=1_specific_ability', 0):,} | "
          f"{e.get('rescued_only_by_generic_matches', 0):,} |")
    e = ex["all"]
    A(f"| **all** | {g2['cards']:,} | {g2['one_bearing_ability']:,} | {g2['two_or_more_bearing']:,} | "
      f"**{pc(g2['rescued_any_ge_0.90'], g2['cards'])}** | {g2['rescued_any_ge_0.80']:,} | {g2['rescued_any_ge_0.70']:,} | "
      f"{g2['all_abilities_ge_0.90_multi']:,} | {e['rescued_with_>=1_specific_ability']:,} | {e['rescued_only_by_generic_matches']:,} |\n")
    A("*Specific* = the ability has >= 3 tokens and its best leaf has <= 300 cards; *generic* = a single bare "
      "token, or a leaf of 500+ cards (`probe_extra.py`). The three thresholds give the same answer to within "
      "four cards: the scores are bimodal. The 1,615 one-ability cards cannot be helped at all (their score "
      "is their blended score), and 1,783 of the 4,175 cards (43%) have no ability >= 0.90 anywhere: "
      "bespoke effects no leaf covers.\n")
    A("Where a rescued card would land if every ability >= 0.90 were placed (distinct leaves): "
      "1 leaf: 1,012 · 2: 1,015 · 3: 294 · 4+: 71.\n")

    # ----------------------------------------------------------------- step 5
    A("## 5. Named cards\n")
    A("Every ability item with its text, token count, best leaf (cards), score and the leaf's branch labels. "
      "The first line of each card is the blended result the current placement used.\n")
    for c in named:
        pl = c["placement"]
        where = ("leaf %s" % pl.get("leaf") if pl.get("method") == "clustered" else
                 "nearby, leaf %s (%.2f)" % (pl["leaf"], pl["similarity"]) if pl.get("method") == "proximity" else
                 "not placed (%s%s)" % (pl.get("reason"), ", best %.2f" % pl["similarity"] if "similarity" in pl else ""))
        A(f"### {c['name']} - {c['status']}; {where}\n")
        for f in c["faces"]:
            bb = f["blended_best_leaf"]
            A(f"Blended: {f['blended_score']:.3f} -> leaf {bb['leaf']} “{bb['phrase'][:40]}” {bb['branches'] or ''}\n")
            A("| ability | text | tokens | score | best leaf (cards) | leaf phrase / branches |")
            A("|---|---|---:|---:|---|---|")
            for a in f["abilities"]:
                t = (a["text"] or "(blank in the data)").replace("|", "/")[:78]
                if a["score"] is None:
                    A(f"| {a['bucket']}#{a['idx']} | {t} | 0 | none | no tokens | |")
                else:
                    bst = a["best"]
                    A(f"| {a['bucket']}#{a['idx']} | {t} | {len(a['tokens'])} | {a['score']:.3f} | "
                      f"{bst['leaf']} ({bst['size']}) | “{bst['phrase'][:36].replace('|', '/')}” {bst['branches'] or '(no branch)'} |")
        if c["name"] in NAMED_NOTES:
            A(f"\n{NAMED_NOTES[c['name']]}")
        A("")
    A("Findings from the table: (1) a high score is not a correct parse, Spark Double scores 1.000 on a parse "
      "that lost its copy effect; (2) bare single-token abilities (`eff:Mana`, `eff:LoseLife`, `eff:Draw`) "
      "match huge leaves perfectly and say little; (3) modal spells list each mode as its own ability item "
      "(Merciless Eviction: one mode scores 0.998, its siblings 0.26-0.30), so 'every ability >= 0.90' is not "
      "meaningful for them; (4) several leaves carry branch labels that do not describe their members "
      "(Eternal Witness under 'Bounce removal', Deep-Slumber Titan under 'Tapper').\n")

    # ----------------------------------------------------------------- step 6
    A("## 6. False rescues: 30 sampled abilities\n")
    A(f"Seeded sample (seed {o['seed']}), one ability per card, drawn from the {o['rescues_ge_0.90']['abilities']:,} "
      f"abilities (on {o['rescues_ge_0.90']['cards']:,} cards) that score >= 0.90 in the unplaced group. "
      "'Members with tokens' = share of the leaf's cards that contain every one of the ability's tokens "
      "(always 100% when the leaf is built on that token set). The verdict column is a hand judgment against "
      "the leaf's member cards.\n")
    A("| # | card | ability | tokens | leaf (cards) | score | verdict |")
    A("|---:|---|---|---:|---|---:|---|")
    tally = {"real": 0, "generic": 0, "wrong": 0}
    for i, s in enumerate(o["false_rescue_sample"], 1):
        verdict, why = VERDICT[s["card"]]
        key = "real" if verdict == "real" else "generic" if verdict == "generic" else "wrong"
        tally[key] += 1
        A(f"| {i} | {s['card']} | {(s['ability'] or '(blank mode)')[:70].replace('|', '/')} | {len(s['tokens'])} | "
          f"{s['leaf']['leaf']} ({s['leaf']['size']}) “{s['leaf']['phrase'][:30]}” | {s['score']:.3f} | **{verdict}**: {why} |")
    A("")
    A(f"**Verdicts: {tally['real']} real and specific, {tally['generic']} real but generic (the ability matches a "
      f"bare-token or catch-all leaf, so the match carries little information), {tally['wrong']} wrong or "
      "artifacts** (counter type invisible to tokens: Charforger, War of the Last Alliance; only the first step "
      "of a reflexive chain tokenised: The Thing, Sanguine Spy).\n")
    r = o["rescues_ge_0.90"]
    A(f"Across all {r['abilities']:,} rescuing abilities: **{pc(r['in_20_largest_leaves'], r['abilities'])} land in "
      f"the 20 largest leaves**; {pc(r['single_token_abilities'], r['abilities'])} are single-token abilities; "
      f"{pc(r['only_top15_df_tokens'], r['abilities'])} use only the 15 most common tokens; the median matched leaf "
      f"has {int(r['leaf_size_percentiles']['50'])} cards. The ten leaves taking the most rescues: "
      f"{', '.join('%s (%s)' % (l, n) for l, n in r['top_leaves'])}. By bare token, the biggest are "
      f"{', '.join('%s %s -> leaf %s (%s cards)' % (t, n, l, s) for l, t, n, s in ex['bare_single_token_rescues_by_token'][:4])}.\n")

    # ----------------------------------------------------------------- step 7
    A("## 7. Clean-parse caveat\n")
    q = o["group2_band_by_quality"]
    A("Every card in the unplaced group is `clean` by definition (the pipeline filters partial, unmodelled and "
      "corrected cards out before placement), so the meaningful split inside it is **clean and unflagged** "
      "versus **clean but flagged by the condition-drop detector** (a clean parse the detector says lost a "
      "condition; 311 cards, 7.4%).\n")
    A("| band | unflagged cards | rescued >= 0.90 | flagged cards | rescued >= 0.90 |")
    A("|---|---:|---:|---:|---:|")
    for name in ("0.70-0.80", "0.50-0.70", "<0.50"):
        u, f = q[name + "|clean_unflagged"], q[name + "|flagged"]
        A(f"| {name} | {u['cards']:,} | {pc(u['rescued_any_ge_0.90'], u['cards'])} | {f['cards']:,} | {pc(f['rescued_any_ge_0.90'], f['cards'])} |")
    fl = ex["rescuing_abilities_individually_flagged_by_detector"]
    A("")
    A(f"Of the {fl['rescuing_abilities']:,} rescuing abilities, **{fl['flagged']} ({fl['flagged']/fl['rescuing_abilities']:.1%}) "
      f"are themselves the item the detector flags** (on {fl['cards']} cards). **No conclusion changes if only "
      "unflagged cards are counted**: the 0.70-0.80 band is 855 of 857 either way (99.8%), and the overall "
      "rescue rate is 56% unflagged against 72% flagged (flagged cards skew toward multi-ability text). "
      "A clean-but-wrong ability (Spark Double) is invisible to this check, so a high score cannot certify an "
      "ability; it can only say the ability looks like a leaf's.\n")
    x = o["partial_unmodelled_extra"]
    A(f"Extra population (not asked, but the caveat's other side): of the {x['cards']:,} partial and unmodelled "
      f"cards, {x['cards_with_a_gap_free_token_bearing_ability']:,} have an ability free of gap nodes and "
      f"{x['cards_with_a_gap_free_ability_ge_0.90']:,} have one scoring >= 0.90. That would place a card on the "
      "part the parser understood while hiding the part it did not. Not recommended.\n")

    # ----------------------------------------------------------------- step 8
    A("## 8. Recommendation\n")
    A("**Build a per-ability layer, narrowly, as an additive 'also fits' layer (a card may appear under several "
      "leaves, never in place of one).**\n")
    A("- **Population:** only the unplaced 'Parsed, no close group found' cards with a blended score of "
      "**0.50 or more** (1,662 cards). 1,363 of them have at least one *specific* match. Do not touch the "
      "2,513 cards below 0.50: only 161 have a specific match, 529 match only generic leaves, 1,760 match "
      "nothing, and most are one-ability cards the scorer cannot help.")
    A("- **Threshold: 0.90.** Scores are bimodal, so 0.80 and 0.70 add four cards and only invite noise.")
    A("- **Per ability, not per card:** list each ability >= 0.90 as 'also fits leaf N (score)', up to the "
      "card's own abilities; do not claim the card 'belongs' to a leaf. Most would show two or three leaves.")
    A("- **Exclude generic matches from the claim** (single bare token, or a leaf of 500+ cards) or show them "
      "as a muted 'also draws / makes tokens'. 712 rescued cards (17%) would otherwise be placed on a "
      "bare `eff:Draw`/`eff:Token`/`eff:Mana` leaf and tell a tester nothing.")
    A("- **Never apply to cards that already have a placement,** to modal spells without handling the modes "
      "(216 cards in the group), or to the 184 abilities the detector flags individually.")
    A("- **Do not extend to partial or unmodelled cards.**")
    A("- **What it would and would not fix.** It would give 1,363 currently suggestion-only cards a real, "
      "specific 'also fits' link, and explain the 0.70-0.80 band honestly: they are two-effect cards, not near "
      "misses. It would not change the 1,783 cards that match nothing, and it inherits the token scheme's "
      "blind spots: counter type, everything after a chain's first effect, replacement declines, and mode-"
      "level abilities.\n")
    A("### Surprises\n")
    A("- The hypothesis was right about the mechanism and wrong about the shape: two perfect matches in different "
      "leaves, not one perfect match and noise.")
    A("- 43% of the group (1,783 cards) has no ability matching any leaf at 0.90, and 1,615 of those are "
      "one-ability cards: genuinely unusual effects, not dilution.")
    A("- Clustered cards are themselves not always above the floor: Tireless Tracker sits in its leaf at "
      "0.779 blended; 5% of clustered multi-ability faces score under 0.71 per ability against their own leaf.")
    A("- 18 abilities in the group (and 116 in the clustered set, mostly replacements) produce no tokens at all.")
    A("- Leaf-label problems surfaced by the scorer, not caused by it: 'Bounce removal' on a graveyard-return "
      "leaf, 'Tapper' on 'enters tapped', and a derived phrase 'Exile target ___' on the cast-with-flash leaf.\n")
    A("### Limits of this probe\n")
    A("The 30-ability false-rescue sample is a sample, and the verdicts are one reader's. 'Specific' and "
      "'generic' use fixed cut-offs (3 tokens, 300 and 500 cards) chosen to be easy to state, not tuned. The "
      "detector flag is the only quality signal beyond the pipeline's own. Nothing was run on cards the "
      "pipeline excludes, other than the partial/unmodelled count above. `build/ability_probe.json` came from "
      "one run; the report generator is deterministic.\n")
    with io.open(os.path.join(HERE, "reports", "ability-placement-probe.md"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(L))
    print("written", sum(len(x) for x in L), "chars")


if __name__ == "__main__":
    main()
