#!/usr/bin/env python3
"""Writes reports/land-denial-diagnosis.md from build/land_denial_probe*.json (diagnosis only)."""
import collections
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
B = os.path.join(HERE, "build")
J = lambda n: json.load(io.open(os.path.join(B, n), encoding="utf-8"))

CORRECT_LEAVES = {41, 317, 433}
GAP_ON_LAND_CLAUSE = {"Bend or Break", "Gerrymandering", "Liliana of the Veil", "Whims of the Fates", "Thieves' Auction",
                      "Dimensional Breach", "Wake of Destruction", "Natural Balance", "Ember Swallower"}


def main():
    d = J("land_denial_probe.json")
    pc = d["per_card"]
    roles = J("land_denial_roles.json")["roles"]
    p2 = J("land_denial_probe2.json")
    p3 = J("land_denial_probe3.json")
    unorg = J("unorganized.json")
    gname = {g["id"]: g["name"] for g in unorg["groups"]}
    core = {o: i for o, i in pc.items() if roles.get(i["name"]) in ("D", "DP", "DB")}

    def cause(i):
        if i["method"] != "unplaced":
            return "placed correctly" if (i["leaf"] in CORRECT_LEAVES) else "wrong-target leaf (placed)"
        if i["group"] == 1:
            return "parse gap (on the land clause)" if i["name"] in GAP_ON_LAND_CLAUSE else "parse gap (elsewhere on the card)"
        if i["group"] == 2:
            s = i["sim"] or 0
            return "no leaf exists (best < 0.50)" if s < 0.50 else "near-miss leaf (0.50-0.80)"
        return "other"
    for i in pc.values():
        i["cause"] = cause(i) if roles.get(i["name"]) in ("D", "DP", "DB") else None
    cc = collections.Counter(i["cause"] for i in core.values())

    L = ["# Mass land denial: why these cards are in \"Not yet organized\"", "",
         "Diagnosis only. Nothing was built, placed or changed; every frozen file is byte-identical. Generated by "
         "`src/report_land_denial.py` from `build/land_denial_probe*.json` (probes: `src/probe_land_denial*.py`). "
         "Oracle tags (`oracle-tags-raw.json`, read in place from `development/versions/card_function_search_v0.2/data`, "
         "dated 2026-07-16, so newer cards carry no tags) are used for MEASUREMENT ONLY and never feed a placement: using "
         "them to place or to validate placement would be circular.", "",
         "**Judgment calls.** The role of each card (destroys many lands, lock, false hit, ...) is my reading of its text; the "
         "regex hits and tag hits are mechanical. The role table is `build/land_denial_roles.json`.", "",
         "## 1. The card list", "",
         f"- text patterns hit **{d['text_pattern_hits']}** in-scope cards; the Scryfall tag `mass-land-denial` has "
         f"{d['mass_land_denial_tag_cards']} cards ({d['mass_land_denial_in_scope']} in scope)",
         f"- list = union = **{d['list']}** cards: **{d['text_only']} found by text only, {d['tag_only']} by tag only, {d['both']} by both**",
         "", "| role | meaning | cards | by text only | by tag only | by both |", "|---|---|---:|---:|---:|---:|"]
    meaning = {"D": "destroys / sacrifices / exiles / bounces all or many lands", "DP": "same through \"all permanents\" or \"half\" effects",
               "DB": "balancing (each player keeps N of each type)", "L": "lock or convert lands; nothing destroyed",
               "S": "single or periodic land loss", "U": "unusual / self-only", "F": "false hit: not about lands"}
    for r in ("D", "DP", "DB", "L", "S", "U", "F"):
        sub = [i for i in pc.values() if roles.get(i["name"]) == r]
        L.append("| %s | %s | %d | %d | %d | %d |" % (r, meaning[r], len(sub), sum(1 for i in sub if i["found_by"] == ["text"]),
                                                       sum(1 for i in sub if i["found_by"] == ["tag"]), sum(1 for i in sub if len(i["found_by"]) == 2)))
    L += ["", "**False hits (30), all from text patterns except 4 tag hits.** The regexes match \"return all nonland permanents\" "
          "(14 bounce cards), \"each player chooses ... sacrifices the rest\" about creatures (Covetous Elegy, Promise of Loyalty, "
          "Single Combat, Stick Together, Archfiend of Depravity), \"destroy all lands\" inside a restriction "
          "(Elspeth Tirel: \"except for lands\"; Scourglass; Street Sweeper), and others. **The tag over-includes in another way:** "
          "37 of its cards only lock or convert lands (Blood Moon, Winter Orb, Stasis, Hokori) and 10 lose one land at a time "
          "(Burning Sands, Stoneshaker Shaman). The tag's own description says it covers \"keep lands tapped, or change\".",
          "", "Core mass land denial (roles D, DP, DB): **%d cards**." % len(core), "",
          "## 2. Per card (core cards; the full 150 are in `build/land_denial_probe.json`)", "",
          "| role | card | found by | status | placement | blended | best ability: score, leaf | gaps | also-fits | cause |",
          "|---|---|---|---|---|---:|---|---:|---:|---|"]
    for r in ("D", "DP", "DB"):
        for i in sorted([x for x in core.values() if roles[x["name"]] == r], key=lambda x: x["name"]):
            ab = sorted([a for a in i["abilities"] if a["score"] is not None], key=lambda a: -a["score"])
            best = ("%.2f, leaf %s \"%s\" (%s cards)" % (ab[0]["score"], ab[0]["best_leaf"], (ab[0]["leaf_phrase"] or "")[:32], ab[0]["leaf_size"])) if ab else "-"
            where = ("Not yet organized: " + gname.get(i["group"], "?")) if i["method"] == "unplaced" else "%s, leaf %s" % (i["method"], i["leaf"])
            L.append("| %s | %s | %s | %s | %s | %s | %s | %d | %d | %s |" % (
                r, i["name"], "+".join(i["found_by"]), i["status"], where,
                ("%.2f" % i["sim"]) if i["sim"] is not None else "-", best, len(i["gaps"]), len(i["also_fits"]), i["cause"]))
    L += ["", "## 3. Cause counts (core cards)", "", "| cause | cards |", "|---|---:|"]
    for k, v in cc.most_common():
        L.append("| %s | %d |" % (k, v))
    L += ["", f"Of the {len(core)}: {sum(1 for i in core.values() if i['method'] != 'unplaced')} are placed and "
              f"{sum(1 for i in core.values() if i['method'] == 'unplaced')} are in Not yet organized. **Wildfire, Obliterate, Jokulhaups "
              "and Upheaval are not in Not yet organized**: they are clustered (leaves 41, 317, 317, 391). Armageddon, Sunder and Ravages of War are.",
          "", "## 4. The hypothesis, checked", "",
          "**Token signatures of the land-relevant ability, by variant** (effect token + target-shape token):", ""]
    for v, c in sorted(p2["variants"].items(), key=lambda kv: -sum(kv[1].values())):
        L.append("- **%s** (%d cards, %d signatures): %s" % (v, sum(c.values()), len(c), "; ".join("%d x `%s`" % (n, s[:90]) for s, n in sorted(c.items(), key=lambda kv: -kv[1]))))
    L += ["", "Corpus document frequency of the key tokens in the clustering: `eff:DestroyAll|tgt:Typed[Land]@Any` **6** faces (Armageddon, "
          "Bust, Catastrophe, Fall of the Thran, Myojin of Infinite Rage, Ravages of War: all HDBSCAN noise), nonbasic variant 2, "
          "`Subtype:Island` variant 3, `eff:Bounce|tgt:Typed[Land]@Any` 3, `eff:ChangeZoneAll|tgt:Typed[Land]@Any` 1, "
          "`eff:DestroyAll|tgt:Or` 23, `eff:Sacrifice|tgt:Typed[Land]@Any` 35.", "",
          "**Clustering only the core cards** (the clustering's tokens, HDBSCAN, minimum size 3):", ""]
    for k, v in p2["cluster"].items():
        L.append("- `%s`: %d of %d cards with features grouped in %d groups" % (k, v["grouped"], v["cards_with_features"], len(v["groups"])))
        for g in v["groups"]:
            L.append("  - %d: %s" % (len(g), ", ".join(g)))
    L += ["", "## 5. The wider problem (diagnostic only; tags are never fed into placement)", "",
          "In scope 34,864 cards, 8,779 unorganized (25.2%%). Tags with at least 5 in-scope cards: %d." % len(p3["tags"]), "",
          "| tag | cards | unorganized | share | groups (1 gap, 2 no close group, ...) |", "|---|---:|---:|---:|---|"]
    for t in p3["tags"][:25]:
        L.append("| %s | %d | %d | %.0f%% | %s |" % (t["slug"], t["n"], t["unorg"], 100 * t["share"], t["groups"]))
    L += ["", "By share (tags with >= 20 cards):", "", "| tag | cards | unorganized | share | groups |", "|---|---:|---:|---:|---|"]
    for t in sorted([t for t in p3["tags"] if t["n"] >= 20], key=lambda t: (-t["share"], -t["unorg"]))[:25]:
        L.append("| %s | %d | %d | %.0f%% | %s |" % (t["slug"], t["n"], t["unorg"], 100 * t["share"], t["groups"]))
    L += ["", "Top 20 by count, what stops the unorganized cards forming a group of their own:", "",
          "| tag | unorganized | in a parse-gap group | distinct effect-type signatures | cards in signatures of >= 5 | loose signatures | cards in loose signatures of >= 5 | with an ability >= 0.90 |",
          "|---|---:|---:|---:|---:|---:|---:|---:|"]
    for t in p3["tags"][:20]:
        g = p3["top20_diag"][t["slug"]]
        L.append("| %s | %d | %d | %d | %d | %d | %d | %d |" % (t["slug"], g["unorg"], g["gap_cards"], g["distinct_effect_sigs"], g["cards_in_sigs_of_5plus"],
                                                              g["distinct_loose_sigs"], g["cards_in_loose_sigs_of_5plus"], g["with_ability_ge_0.90"]))
    L += ["", "## 6. The earlier no-match measurement, re-run", "",
          "Population %d cards; %d of the %d core land denial cards are in it." % (p3["pop"], p3["core_in_pop"], len(core)), "",
          "| signature | min size | groups | cards in groups | cards in groups of >= 5 | groups with a specific shared token | cards in those (>= 5) | groups with an effect token | cards in those (>= 5) | core cards grouped |",
          "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
    for name, blk in (("card_features (earlier)", p3["baseline"]), ("looser", p3["loose"])):
        for m in ("5", "3"):
            v = blk[m]
            L.append("| %s | %s | %d | %d | %d | %d | %d | %d | %d | %d |" % (name, m, v["groups"], v["cards_in_groups"], v["cards_in_groups_ge5"],
                     v["groups_with_specific_shared_token"], v["cards_in_ge5_groups_with_specific_token"], v["groups_with_effect_token"],
                     v["cards_in_ge5_groups_with_effect_token"], v["core_cards_grouped"]))
    L.append("")
    with io.open(os.path.join(HERE, "reports", "land-denial-diagnosis.md"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(L) + "\n")
    print(json.dumps(dict(cc), indent=1))


if __name__ == "__main__":
    main()
